---
- name: install dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=86400 state=present
  with_items:
    - gcc
    - make
    - libc6-dev

- name: download redis
  get_url: url=http://download.redis.io/releases/redis-{{ redis_version }}.tar.gz
           dest=/usr/local/src/redis-{{ redis_version }}.tar.gz
  when: not redis_tarball
  
- name: upload redis
  copy: src={{ redis_tarball }}
        dest=/usr/local/src/redis-{{ redis_version }}.tar.gz  
  when: redis_tarball

- name: extract redis tarball
  shell: tar xf /usr/local/src/redis-{{ redis_version }}.tar.gz -C /usr/local/src
         creates=/usr/local/src/redis-{{ redis_version }}

- name: compile redis
  command: make -j5
           chdir=/usr/local/src/redis-{{ redis_version }}
           creates=/usr/local/src/redis-{{ redis_version }}/src/redis-server

- name: create redis install directory
  file: path={{ redis_install_dir }} state=directory

- name: create /etc/redis
  file: path=/etc/redis state=directory

- name: add redis user
  user:
    name={{ redis_user }}
    comment="Redis"
    home={{ redis_install_dir }}
    shell=/bin/false
    system=yes

- name: create /var/run/redis
  file: path=/var/run/redis state=directory
        owner={{ redis_user }}

- name: install redis
  command: make PREFIX={{ redis_install_dir }} install
           chdir=/usr/local/src/redis-{{ redis_version }}
           creates={{ redis_install_dir }}/bin/redis-server

- name: create phpredis client folder
  command: mkdir /tmp/phpredis force=no  creates=/tmp/phpredis

- name: download latest stable phpredis client
  get_url: url=https://github.com/nicolasff/phpredis/archive/master.zip dest=/tmp/phpredis/master.zip

- name: go to folder phpredis and unzip
  command: chdir=/tmp/phpredis unzip master.zip

- name: Do Phpize Redis
  command: chdir=/tmp/phpredis/phpredis-master phpize

- name: Configure
  command: chdir=/tmp/phpredis/phpredis-master ./configure

- name: Make Redis
  command: chdir=/tmp/phpredis/phpredis-master make 

- name: Make Install The Redis
  command: chdir=/tmp/phpredis/phpredis-master make install

- name: Add redis.so to php modules
  copy: src=phpredis.ini dest=/etc/php.d/phpredis.ini force=yes